channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - fastqc=0.11.9
  - sra-tools=2.10.1
# Add tools here
# Specify python version (not required but can help with downstream conflicts)
  - python=3.7.6

# The workflow manager
  - snakemake-minimal=5.10.0

# For visualizing workflows
  - graphviz=2.42.3
  - xorg-libxrender
  - xorg-libxpm

# For downloading files
  - wget=1.20.1